### ISSUE TITLE
When getting authenticated: ssl.SSLError: [Errno 185090050]

### ISSUE THREAD

**Issue by gevrey** [vinitkumar/googlecl#262]
Enter the auth code: ******
Traceback (most recent call last):
  File "src/google.py", line 956, in <module>
    main()
  File "src/google.py", line 942, in main
    run_once(options, args)
  File "src/google.py", line 707, in run_once
    client = auth.oauth_login()
  File "/home/cri/dev/googlecl/src/googlecl/authenticate.py", line 34, in oauth_login
    credentials = flow.step2_exchange(auth_code)
  File "build/bdist.linux-i686/egg/oauth2client/_helpers.py", line 133, in positional_wrapper
  File "build/bdist.linux-i686/egg/oauth2client/client.py", line 2047, in step2_exchange
  File "build/bdist.linux-i686/egg/oauth2client/transport.py", line 282, in request
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 241, in __init__
    ciphers)
ssl.SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

**Comment by vinitkumar** [comment]
Which python version are you working on? If possible, use the latest.

**Comment by gevrey** [comment]
Python 2.7.6

**Comment by vinitkumar** [comment]
@gevrey It's quite old. Consider updating to Python 2.7.13 and check again.
