### ISSUE TITLE
ssl.SSLError

### ISSUE THREAD

**Issue by gevrey** [vinitkumar/googlecl#264]
Hello.
Due to some issue with my Samba server, I had to downgrade Python to 2.7.6 to fix it.
Then I have re-installed Python 2.7.13 from sources.
Since then, I see the following error. Can you please suggest a solution?

cri@wscg8:/tmp/Python-2.7.13$ python -V
Python 2.7.13
cri@wscg8:/tmp/Python-2.7.13$ /home/cri/dev/googlecl/src/google picasa post --src image.jpeg --title "Test"
Refreshing access_token
Traceback (most recent call last):
  File "/home/cri/dev/googlecl/src/google", line 956, in <module>
    main()
  File "/home/cri/dev/googlecl/src/google", line 942, in main
    run_once(options, args)
  File "/home/cri/dev/googlecl/src/google", line 707, in run_once
    client = auth.oauth_login()
  File "/home/cri/dev/googlecl/src/googlecl/authenticate.py", line 36, in oauth_login
    return self.refresh_creds(credentials, 0)
  File "/home/cri/dev/googlecl/src/googlecl/authenticate.py", line 41, in refresh_creds
    credentials.refresh(httplib2.Http())
  File "build/bdist.linux-i686/egg/oauth2client/client.py", line 541, in refresh
  File "build/bdist.linux-i686/egg/oauth2client/client.py", line 756, in _refresh
  File "build/bdist.linux-i686/egg/oauth2client/client.py", line 775, in _do_refresh_request
  File "build/bdist.linux-i686/egg/oauth2client/transport.py", line 282, in request
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 241, in __init__
    ciphers)
ssl.SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
cri@wscg8:/tmp/Python-2.7.13$

**Comment by gevrey** [comment]
Wrong version of Python was used.
Had to change to /usr/local/bin/python in src/google
